### ISSUE TITLE
[TEAM] 20200601 mon, scrum

### ISSUE THREAD

**Issue by delmaSong** [codesquad-member-2020/airbnb-06#56]
### 주말동안 한 일
- CalendarViewController에서 선택한 체크인-아웃 날짜를 메인화면에 반영
- JK 피드백 반영 -> 네트워크 관련 

### 오늘 할 일 
- 실서버에 요청시 제대로 응답이 돌아오지 않는 이슈가 있어서 이거 해결하기.. 

### 컨디션 
- VERY GOOD

**Comment by david215** [comment]
### 주말 동안 한 일
- 토: 가격 그래프 API 구현
- 일: 즐겨찾기 API 일부 구현
### 오늘 할 일
- 즐겨찾기 API 구현 마무리
- 예약 목록 및 상세 보기 API 구현 시작
### 컨디션
- 집에만 있으니 생산성이 떨어지는 느낌...
- 그래도 쥬쥬랑 같이 있어서 좋기도 하고...
- 장단이 있는 듯 하다.

**Comment by idevjinie** [comment]
### 주말 동안 한 일
- 가격 그래프 및 슬라이더 구성
- Xcode 에러 해결 시도
  - 소통은 중요한 것

### 오늘 할 일
- 가격 그래프 및 슬라이더 기능 보완
- 네트워크 연동

### 컨디션
- 장어 먹어서 좋음

**Comment by delmaSong** [comment]
다들 귀엽다.. 장어 먹어서 기분 좋고.,, 쥬쥬랑 있어서 좋고..
