### ISSUE TITLE
[TEAM] 20200602 tue, scrum

### ISSUE THREAD

**Issue by delmaSong** [codesquad-member-2020/airbnb-06#57]
### 어제 한 일 ( 어제의 성취와 어려웠던 것!? 어떻게 해결했는지 .. )

- 실 서버로 네트워크 요청 후 응답 못받던 에러 해결
- iOS 티셔츠 디자인....

### 오늘 할 일
- 인원 선택 화면 기능
- 선택한 인원을 메인 화면에 반영
- 하트 토글 기능
- 필터 적용한 데이터로 서버에 요청 

### 컨디션
- 잠을 잘 못잤으나... 나름..괜춘..

**Comment by david215** [comment]
### 어제 한 일
- 즐겨찾기 API 마무리
- 예약 목록, 예약 상세 API 구현
### 오늘 할 일
- 예약 / 취소 API 구현
- 예외처리 추가 (날짜 체크 등등)
- OAuth 라이브러리로 만들어서 분리?
### 컨디션
- 끝이 보여서 신나네요~

**Comment by idevjinie** [comment]
### 어제 한 일
- 가격 범위 그래프 및 슬라이더 인터페이스 구성
- Core Graphics 공부

### 오늘 할 일
- 가격 범위 그래프 및 슬라이더 기능 구현
- 네트워크 연동

### 컨디션
- 먹구름 덕분에 차분함
